# Generated by Django 6.0.2 on 2026-02-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_booking_total_days_alter_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
