# Generated by Django 6.0.2 on 2026-03-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
