# Generated by Django 6.0.2 on 2026-03-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chatroom',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
