# Generated by Django 6.0.2 on 2026-03-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_message_chatroom_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='men', max_length=10),
            preserve_default=False,
        ),
    ]
