# Generated by Django 6.0.1 on 2026-03-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_userprofile_address_remove_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='end_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='start_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
