# Generated by Django 6.0.1 on 2026-04-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_booking_id_alter_category_id_alter_clothing_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='rental_days',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
