# Generated by Django 6.0.1 on 2026-04-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_cartitem_rental_days_cartitem_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='tracking_status',
            field=models.IntegerField(default=1),
        ),
    ]
