# Generated by Django 6.0.1 on 2026-04-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rentalorder_size_rentalorder_tracking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('cod', 'Cash on Delivery'), ('wallet', 'Wallet')], default='cod', max_length=10),
        ),
    ]
