# Generated by Django 6.0.1 on 2026-04-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_rentalorder_status_wallet_wallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wallet_balance',
        ),
    ]
