# Generated by Django 6.0.1 on 2026-04-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_rentalorder_status_returnrequest_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalorder',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('confirmed', 'Confirmed'), ('out_for_delivery', 'Out for Delivery'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('in_use', 'In Use'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('refund_completed', 'Refund Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
