"""
Django settings for rental_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fai9kzzdbx31h^6^_gif7i8ktk!n^)kd!^s^c=kx*(d+%0e=di'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rental_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.cart_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'rental_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'rental_db',
        'USER': 'root',
        'PASSWORD': 'Shivam@212',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/




STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

RAZORPAY_KEY_ID = "rzp_test_SWD6XmdT3zYnrA"
RAZORPAY_KEY_SECRET = "NJCzSc3NPtg3sHxbaggPcEnS"

# Auth settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Messages
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}


# JAZZMIN SETTINGS
JAZZMIN_SETTINGS = {
    # ── Branding ────────────────────────────────────────────────────────────
    "site_title": "PRORENT Admin",
    "site_header": "PRORENT",
    "site_brand": "PRORENT",
    "site_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Welcome back to PRORENT Admin",
    "copyright": "© 2025 PRORENT Ltd. All rights reserved.",

    # ── Top Search ───────────────────────────────────────────────────────────
    "search_model": ["auth.User", "store.Clothing", "store.RentalOrder"],
    "user_avatar": None,

    # ── Top Menu Links ───────────────────────────────────────────────────────
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
        {"model": "auth.User"},
        {"model": "store.RentalOrder"},
        {"model": "store.Clothing"},
    ],

    # ── User Menu (top-right dropdown) ───────────────────────────────────────
    "usermenu_links": [
        {"name": "View Site", "url": "/", "new_window": True, "icon": "fas fa-home"},
    ],

    # ── Sidebar ──────────────────────────────────────────────────────────────
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # Custom app ordering in sidebar
    "order_with_respect_to": [
        "auth",
        "store",
        "store.Clothing",
        "store.Category",
        "store.RentalOrder",
        "store.RazorpayPayment",
        "store.Booking",
        "store.UserProfile",
        "store.UserAddress",
        "store.Review",
        "store.Payment",
    ],

    # Custom links added to specific app groups
    "custom_links": {
        "store": [{
            "name": "View Store",
            "url": "/browse/",
            "icon": "fas fa-store",
            "new_window": True,
        }],
    },

    # ── Icons ────────────────────────────────────────────────────────────────
    "icons": {
        "auth":                     "fas fa-shield-alt",
        "auth.user":                "fas fa-user",
        "auth.group":               "fas fa-users",
        "store.userprofile":        "fas fa-id-card",
        "store.category":           "fas fa-layer-group",
        "store.clothing":           "fas fa-tshirt",
        "store.booking":            "fas fa-calendar-check",
        "store.payment":            "fas fa-credit-card",
        "store.review":             "fas fa-star",
        "store.useraddress":        "fas fa-map-marker-alt",
        "store.rentalorder":        "fas fa-shopping-basket",
        "store.razorpaypayment":    "fas fa-rupee-sign",
        "store.cart":               "fas fa-shopping-cart",
        "store.cartitem":           "fas fa-box",
    },
    "default_icon_parents":  "fas fa-caret-right",
    "default_icon_children": "fas fa-circle-notch",

    # ── Misc ─────────────────────────────────────────────────────────────────
    "related_modal_active":         True,
    "custom_css":                   None,
    "custom_js":                    None,
    "use_google_fonts_cdn":         True,
    "show_ui_builder":              False,
    "changeform_format":            "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user":  "collapsible",
        "auth.group": "vertical_tabs",
    },
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    # ── Bootswatch Dark Theme ────────────────────────────────────────────────
    "theme":              "darkly",      # Full dark Bootswatch theme
    "default_theme_mode": "dark",        # Always start in dark mode

    # ── Navbar ───────────────────────────────────────────────────────────────
    "navbar":             "navbar-dark",
    "navbar_fixed":        True,
    "no_navbar_border":    True,
    "navbar_small_text":   False,

    # ── Brand ────────────────────────────────────────────────────────────────
    "brand_colour":       "navbar-dark",
    "brand_small_text":   False,

    # ── Sidebar ──────────────────────────────────────────────────────────────
    "sidebar":                    "sidebar-dark-warning",
    "sidebar_fixed":               True,
    "sidebar_nav_small_text":      False,
    "sidebar_disable_expand":      False,
    "sidebar_nav_child_indent":    True,
    "sidebar_nav_compact_style":   True,
    "sidebar_nav_legacy_style":    False,
    "sidebar_nav_flat_style":      False,

    # ── Accent / Buttons ─────────────────────────────────────────────────────
    "accent":             "accent-warning",

    # ── Body ─────────────────────────────────────────────────────────────────
    "body_small_text":    False,
    "footer_small_text":  False,
}

# ── Razorpay ──────────────────────────────────────────────────────────────────
# Replace these with your actual Razorpay Dashboard keys.
# Test keys start with rzp_test_  |  Live keys start with rzp_live_
RAZORPAY_KEY_ID     = 'rzp_test_SWD6XmdT3zYnrA'       # exposed to frontend
RAZORPAY_KEY_SECRET = 'NJCzSc3NPtg3sHxbaggPcEnS'             # NEVER expose this